language: ruby
rvm:
  - 2.4
cache: bundler
script: bundle exec bin/rake test
env:
  - DISABLE_SPRING=1

before_install:
  - cp config/database.travis.yml config/database.yml
  - bundle exec bin/rake db:create

services:
  - mysql
