language: ruby
rvm:
  - 2.4
cache: bundler
script: bundle exec rake test
env:
  - DISABLE_SPRING=1

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create

services:
  - mysql
